# Generated by Django 3.2 on 2022-09-28 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=256, null=True)),
                ('book', models.CharField(max_length=256, null=True)),
                ('add_info', models.TextField(null=True)),
                ('active', models.SmallIntegerField(default=1)),
                ('likes', models.IntegerField(default=0)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snippets',
            },
        ),
    ]
