# Generated by Django 3.2 on 2022-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippettags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(to='api.Tags'),
        ),
        migrations.DeleteModel(
            name='SnippetTags',
        ),
    ]
