# Generated by Django 3.2 on 2022-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_snippetlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='likes',
        ),
    ]
